server:
  port: 8061
  
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8060
#          jwk-set-uri: http://localhost:8060/.well-known/jwks.json
#          audiences:
#            local: http://localhost:8080
  mail:
    host: smtp.office365.com
    username: temp2710@outlook.com
    password: Temp@2710
    protocol: smtp
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
